### ISSUE TITLE
Add link to v5 on the main v6 description page

### ISSUE THREAD

**Issue by GOS-Heli** [dasher-project/dasher-web#131]
Hi,

It took me 3 google searches, and 20 pages to find the link.. And I'm a little bit familliar to github
What is it if you are llow computer skilled, abandon ?

Suggestion :

**Please find old v5 downlood link **(not developped anymore)**** 
[[[[[]([](https://github.com/dasher-project/dasher/releases)
)
]([](https://github.com/dasher-project/dasher/releases)
)
](https://github.com/dasher-project/dasher/releases)](https://github.com/dasher-project/dasher/releases)

Thx

**Comment by PapeCoding** [comment]
@sjjhsjjh Can you do that? I unfortunately don't have any write access to this repo
