### ISSUE TITLE
Re-implement everything in GDScript for the Godot game engine

### ISSUE THREAD

**Issue by goatchurchprime** [dasher-project/dasher-web#54]
The reasons for this are:
1. The code for the application would be much simpler to develop and make pretty.  
2. The system could be deployed as a component a lot more widely to applicable places than when it is a web-app.

Your current web-based implementation would be replaced by the Godot HTML5 export.  And, additionally, the same code can automatically be built for all other major platforms, so the electron deployment becomes redundant.

However, the real win is that Dasher could be used as a component in a lot of game-type applications (non-games are often built in games engines because of the development environment).  Often the defining characteristic of these are that the user is operating the computer through a controller or joystick instead of a keyboard.  Sometimes, however, it's necessary to write notes or messages, and then you have to do it letter by letter using the joystick on a virtual keyboard.  

The application which brought me here is VR, where you are effectively blindfolded and usually have two controllers (6-DOF joysticks) in your hands.  There is no keyboard, but it's the case that you sometimes need to type and the only option is the joystick virtual keyboard method.  

More recent VR and AR applications work using hand tracking based on image recognition cameras on the front of the headset, so they can detect your hand 
or finger waving up and down and be quite convenient.

VR is very well supported by Godot now (it's what I work on most of the time), and it deploys to WebXR, where the whole system is accessed through a web-page.  

If you don't want to look at Godot, there is a whole javascript-based WebVR meeting system called Mozilla Hubs.  You should look at making Dasher a module for that, for the users in VR, if anything else.  If you get in touch I can give you a tour round it all.

**Comment by Zireael07** [comment]
Godot is a very good game engine... but I don't think reimplementing everything is needed for the more general use case. For VR, you do have a point, but then it would be better to use something outside Godot that could be used from any other VR-compatible engine.
