### ISSUE TITLE
Eyegaze Support

### ISSUE THREAD

**Issue by willwade** [dasher-project/dasher-web#99]
Just to be clear.. This needs discussion! Im dumping all things Eyegaze that we can find here. Basically we need to support it somehow (pending the UX feedback and plan in around Milestone 4). 

-  Look at "Backward Compatibility" in v5 Notes [here](https://docs.google.com/document/d/1TwDCWIh5KDulHtPyvSTjr-dPzJ5C8mgxmNhsXUwONR0/edit#heading=h.hbnleoilp9wl)
- See Proposal for Automatic Calibration [here](http://www.inference.org.uk/dasher/development/Calibration.html)
- [Fast Hands Free Writing - really focusing on gaze](http://www.inference.org.uk/mackay/abstracts/eyeshortpaper.html)
- [Presentation for COGAIN](http://www.inference.org.uk/dasher/presentations/cogain/) (Cogain was the European consortium about developing Eyegaze for AAC). 

### Windows Only

- https://eyetechds.com TM5, Eyeon
- https://uk.tobiidynavox.com - Tobii range of IS5 cameras. Just note - you cant use their developer units for AAC. 
- [Alea Intelligaze](https://www.intelligaze.com/en/pages/en/products/intelligaze.php)
- [Eyegaze Edge](https://eyegaze.com/products/eyegaze-edge/) & Encore

### iOS, Windows, Mac (HID)
 
- https://www.irisbond.com - Hiru

**[properties of different trackers](https://docs.google.com/spreadsheets/u/0/d/1K4CnWljBHRM1b8SKCrevRpP-KZJ6CVdOhURjvQQ4464/htmlview)**

**Comment by gavinhenderson** [comment]
Closing this, as we should do this via the new RFC system
